/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiFrames.framseDB;

import Tester.Client;
import java.awt.Color;
import java.lang.reflect.InvocationTargetException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class MainGUI extends javax.swing.JFrame {

   
                private Connection con = null;
                private Statement stm = null;
                private ResultSet rst = null;
                private PreparedStatement pst = null;
    /**
     * Creates new form MainGUI
     */
    public MainGUI() throws ClassNotFoundException, SQLException {
        initComponents();
        setComponentsPref();
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        showClientSource();
       
    }
    public ArrayList<Client> userList() throws ClassNotFoundException, SQLException{
        ArrayList<Client> clientList = new ArrayList();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
                   String url = "jdbc:mysql://localhost:3306/kursValyut?useUnicode=true&relaxAutoCommit=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC";
                    con = DriverManager.getConnection(url, "root", "toor");
                   String query = "Select * from Client";
                   
                    stm = con.createStatement();
                    rst = stm.executeQuery(query);
                   Client client;
                   
                   while (rst.next()){
                       client = new Client(rst.getInt("Code_client"), rst.getString("Name_client"), rst.getInt("Passport"));
                       clientList.add(client);
                   }
                   
                   String query1 = "SELECT name_staff FROM staff";
                   rst = stm.executeQuery(query1);
                   ResultSetMetaData meta = rst.getMetaData();
                   int items = meta.getColumnCount();
                   while(rst.next()){
                       selectKassir.addItem(rst.getString("name_staff"));
                           
                   }
                  
        }
        catch (Exception e){
            e.printStackTrace();
            System.out.println(e);
        }
        return clientList;
    }
    public void showClientSource() throws ClassNotFoundException, SQLException{
        ArrayList<Client> showClientSource = userList();
        DefaultTableModel model = (DefaultTableModel) tableClient.getModel();
        
        Object[] rows = new Object[3];
        for(int i =0; i < showClientSource.size(); i++){
            rows[0] = showClientSource.get(i).getID();
            rows[1] = showClientSource.get(i).getName();
            rows[2] = showClientSource.get(i).getPassport();
            model.addRow(rows);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_oper = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_addClient = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_search = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        userSidePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        buttonAdd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        fieldGetName = new javax.swing.JTextField();
        fieldGetPassport = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fieldGetContract = new javax.swing.JTextField();
        fieldGetDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        selectKassir = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelUSD = new javax.swing.JLabel();
        jLabelEU = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableClient = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1030, 530));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_oper.setBackground(new java.awt.Color(64, 43, 100));
        btn_oper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_operMouseClicked(evt);
            }
        });
        btn_oper.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GuiFrames/framseDB/images/icons8-money.png"))); // NOI18N
        jLabel1.setText("Последные операции");
        btn_oper.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 24, 178, 26));

        jPanel1.add(btn_oper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 290, -1));

        btn_addClient.setBackground(new java.awt.Color(64, 43, 100));
        btn_addClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_addClientMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addClientMouseClicked(evt);
            }
        });
        btn_addClient.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GuiFrames/framseDB/images/icons8-add_user_male.png"))); // NOI18N
        jLabel3.setText("Новый пользователь");
        btn_addClient.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 20, 173, 24));

        jPanel1.add(btn_addClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 290, 50));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 160, 40));

        btn_search.setBackground(new java.awt.Color(64, 43, 100));
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_searchMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
        });
        btn_search.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GuiFrames/framseDB/images/icons8-search.png"))); // NOI18N
        jLabel4.setText("Пользователь");
        btn_search.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 26, 167, 24));

        jPanel1.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 290, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 230, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 290, 530));

        userSidePanel.setBackground(new java.awt.Color(51, 0, 102));
        userSidePanel.setDoubleBuffered(false);
        userSidePanel.setRequestFocusEnabled(false);
        userSidePanel.setVerifyInputWhenFocusTarget(false);
        userSidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GuiFrames/framseDB/images/icons8-add_user_male_1.png"))); // NOI18N
        userSidePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 56, -1, -1));

        buttonAdd.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        buttonAdd.setForeground(new java.awt.Color(255, 255, 255));
        buttonAdd.setText("ДОБАВИТЬ");
        buttonAdd.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        buttonAdd.setContentAreaFilled(false);
        buttonAdd.setRequestFocusEnabled(false);
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });
        userSidePanel.add(buttonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 443, 110, -1));

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ОТМЕНИТЬ");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jButton2.setContentAreaFilled(false);
        jButton2.setRequestFocusEnabled(false);
        userSidePanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 443, 120, -1));

        getContentPane().add(userSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 530));

        jPanel4.setVisible(false);
        jPanel4.setBackground(new java.awt.Color(99, 103, 195));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(fieldGetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 211, 36));
        jPanel4.add(fieldGetPassport, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 211, 35));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("          Клиент");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jLabel9.setFocusable(false);
        jLabel9.setRequestFocusEnabled(false);
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 211, 29));

        fieldGetContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldGetContractActionPerformed(evt);
            }
        });
        jPanel4.add(fieldGetContract, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 227, 36));
        jPanel4.add(fieldGetDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 227, 35));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ФИО");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 180, 57, 24));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ПАСПОРТ");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 340, -1, 25));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("НОМЕР ДОГОВОРА");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, 24));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ДАТА");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Кассир");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 100, -1));

        selectKassir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectKassirActionPerformed(evt);
            }
        });
        jPanel4.add(selectKassir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 224, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 740, 530));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(122, 72, 221));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Доллар $");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 31));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Евро     €");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 69, 32));

        jLabelUSD.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelUSD.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabelUSD, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 119, 31));

        jLabelEU.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelEU.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabelEU, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 110, 30));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 740, 120));

        tableClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ФИО", "ПАСПОРТ"
            }
        ));
        tableClient.setGridColor(new java.awt.Color(102, 102, 102));
        tableClient.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tableClient.setShowGrid(true);
        tableClient.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tableClient);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 740, 360));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 740, 530));

        jPanel5.setBackground(new java.awt.Color(78, 121, 163));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GuiFrames/framseDB/images/icons8-close_window.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.setDefaultCapable(false);
        jButton3.setFocusable(false);
        jButton3.setRequestFocusEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 6, 40, 40));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ФИО");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 64, -1, -1));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ПАСПОРТ");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 159, -1, 26));

        jLabel15.setText("jLabel15");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 260, -1, -1));

        jLabel16.setText("jLabel16");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 385, -1, -1));

        jLabel17.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 64, 405, 28));

        jLabel18.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 159, 405, 26));

        jLabel19.setText("jLabel19");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 260, -1, -1));

        jLabel20.setText("jLabel20");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 385, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 740, 530));

        jPanel6.setVisible(false);
        jPanel6.setBackground(new java.awt.Color(78, 121, 163));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("ФИО");
        jLabel21.setToolTipText("");
        jLabel21.setRequestFocusEnabled(false);
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 25, 158, 29));

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("ДОГОВОР");
        jLabel22.setRequestFocusEnabled(false);
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 158, 38));

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("ДАТА ОПЕРАЦИИ");
        jLabel23.setRequestFocusEnabled(false);
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 38));

        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jTextField1.setRequestFocusEnabled(false);
        jPanel6.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 25, 300, 30));

        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jTextField2.setRequestFocusEnabled(false);
        jPanel6.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 90, 300, 30));

        jTextField3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jTextField3.setRequestFocusEnabled(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 150, 300, 30));

        jButton4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Поиск");
        jButton4.setBorder(new javax.swing.border.MatteBorder(null));
        jButton4.setContentAreaFilled(false);
        jButton4.setRequestFocusEnabled(false);
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 97, 30));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GuiFrames/framseDB/images/icons8-close_window.png"))); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setDefaultCapable(false);
        jButton6.setRequestFocusEnabled(false);
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 6, 42, -1));

        jTable1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ФИО", "ПАСПОРТ", "ПОКУПКА", "ДОГОВОР", "ДАТА", "КАССИР"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(102, 102, 102));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(0, 204, 204));
        jTable1.setShowGrid(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 700, 260));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 740, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents
int x = 290;
    
    private void btn_operMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_operMouseClicked
        // TODO add your handling code here:
        setColor(btn_oper);
        resetColor(btn_addClient);
        resetColor(btn_search);
        jPanel3.setVisible(true);
        
        
    }//GEN-LAST:event_btn_operMouseClicked

    private void btn_addClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addClientMouseClicked
        // TODO add your handling code here:
        setColor(btn_addClient);
        resetColor(btn_search);
        resetColor(btn_oper);
        
//        if (x == 290){
//            jPanel1.show();
//            jPanel1.setSize(x,530);
//            Thread move1 = new Thread(){
//                @Override 
//                public void run(){
//                    try{
//                        for (int i = 0; i >= x; i --){
//                            Thread.sleep(1);
//                            jPanel1.setSize(i,530);
//                        }
//                    }
//                    catch(Exception e ){
//                        
//                    }
//                }
//            };
//            move1.start();
//            x =0;
//        }
//        jPanel4.setVisible(true);
                  
            
        
    }//GEN-LAST:event_btn_addClientMouseClicked

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseClicked
        // TODO add your handling code here:
        setColor(btn_search);
        resetColor(btn_addClient);
        resetColor(btn_oper);
        
    }//GEN-LAST:event_btn_searchMouseClicked
        int px = 740;
    private void btn_addClientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addClientMousePressed
        // TODO add your handling code here:
       // jPanel4.setVisible(true);
//       setColor(btn_addClient);
//        resetColor(btn_search);
//        resetColor(btn_oper);
        
//       if (x == 290 || px == 740 ){
//           
//            userSidePanel.show();
//            jPanel4.show();
//            userSidePanel.setSize(x,530);
//            jPanel4.setSize(px,530);
//            Thread move1 = new Thread(){
//                @Override 
//                public void run(){
//                    try{
//                        for (int i=0; i>= x; i --){
//                            Thread.sleep(1);
//                            jPanel1.setSize(i,530);
//                        }
//                        for (int j=0; j>= px; j--){
//                            Thread.sleep(1);
//                            jPanel3.setSize(j, 530);
//                        }
//                    }
//                    catch(Exception e ){
//                        
//                    }
//                }
//            };
//            move1.start();
//            x =0;
//            px =0;
            jPanel1.setVisible(false);
            jPanel3.setVisible(false);
            userSidePanel.setVisible(true);
            jPanel4.setVisible(true);
        
       //userSidePanel.setVisible(true);
        
        
        
    }//GEN-LAST:event_btn_addClientMousePressed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:
//        if (jPanel4.isShowing()){
//            
//        
//        if (x == 0 || px == 0 ){   
//        jPanel1.show();
//            jPanel3.show();
//            jPanel1.setSize(x,530);
//            jPanel3.setSize(px,530);
//            Thread move1 = new Thread(){
//                @Override 
//                public void run(){
//                    try{
//                        for (int i=0; i <= x; i++){
//                            Thread.sleep(1);
//                            jPanel1.setSize(i,530);
//                        }
//                        for (int j=0; j <= px; j++){
//                            Thread.sleep(1);
//                            jPanel3.setSize(j, 530);
//                        }
//                    }
//                    catch(Exception e ){
//                        
//                    }
//                }
//            };
//            move1.start();
//            x =290;
//            px =740;
           // userSidePanel.setVisible(false);
           // jPanel4.setVisible(false);
            //jPanel1.setVisible(true);
            //jPanel3.setVisible(true);
            try{
                
                   connectInsert();
                      
                  
                    
                    
            }
            catch(Exception e){
                e.printStackTrace();
                System.out.println(e);
//                JOptionPane.showMessageDialog(null, e.getMessage(), "Connection feild...", JOptionPane.ERROR_MESSAGE);
            }
            
        
        
    }//GEN-LAST:event_buttonAddActionPerformed

    private void btn_searchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMousePressed
        // TODO add your handling code here:
        jPanel5.setVisible(true);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
                Connection con ;
                Statement stm;
                ResultSet rst;
                String url = "jdbc:mysql://localhost:3306/kursValyut";
                
                try{
                    
                    
                }catch(Exception e ){
                    e.printStackTrace();
                    System.out.print(e);
//                    JOptionPane.showMessageDialog(null, e.getMessage(), "Cannot support to data base ", JOptionPane.ERROR_MESSAGE );
                }
                
    }//GEN-LAST:event_btn_searchMousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jPanel5.setVisible(false);
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void fieldGetContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldGetContractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldGetContractActionPerformed

    private void selectKassirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectKassirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectKassirActionPerformed

    public void setColor(JPanel panel){
        panel.setBackground(new Color(85,65,118));
        
    }
    public void resetColor(JPanel panel){
        panel.setBackground(new Color(64,43,100));
    }
    public void setComponentsPref(){
        jTable1.getTableHeader().setBackground(Color.BLUE);
        jTable1.setBackground(Color.WHITE);
        jTable1.setRowHeight(25);        
    }
    
    public void connectInsert() throws ClassNotFoundException, NoSuchMethodException, InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException{
        
       String url = "jdbc:mysql://localhost:3306/kursValyut?useUnicode=true&relaxAutoCommit=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC";        
       String user = "root";
       String password = "toor";
       
       
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver").getDeclaredConstructor().newInstance();
            con = DriverManager.getConnection(url,user,password);
            //con.setAutoCommit(false);
              String sql = "INSERT INTO Client( name_client, passport) VALUES(?,?)";
              String sql1 = "INSERT INTO Contract( id_contract, conclusion_date, code_staff) VALUES(?,now(), ?)";
              
              pst = con.prepareStatement(sql);
              pst.setString(1, fieldGetName.getText());
              pst.setInt(2, Integer.parseInt(fieldGetPassport.getText()));
             
              
              pst = con.prepareStatement(sql1);
              pst.setInt(1, Integer.parseInt(fieldGetContract.getText()));
             // pst.setString(2, fieldGetDate.getText());
              pst.setInt(2, getIdKassir());
               
             
              
              pst.executeUpdate();            
        }catch(Exception e){
            e.printStackTrace();
            System.out.print(e);
           //JOptionPane.showMessageDialog(null, e.getMessage(), "Connection feild...", JOptionPane.ERROR_MESSAGE);
        }
       
    }
    
    public void connectDelete() throws ClassNotFoundException{
       String url = "jdbc:mysql://localhost:3306/kursValyut?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC";        
       String user = "root";
       String password = "toor";
       int rsl = jTable1.getSelectedRow();
       String sel = (String) jTable1.getModel().getValueAt(rsl, 0);
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(url,user,password);
            con.setAutoCommit(false);
              String sql = "DELETE from Client WHERE name_client= " + sel;
              pst = con.prepareStatement(sql);
              pst.executeUpdate();
              con.commit();
        }catch(Exception e){
            e.printStackTrace();
            System.out.println(e);
           //JOptionPane.showMessageDialog(null, e.getMessage(), "Connection feild...", JOptionPane.ERROR_MESSAGE);
        }
    }
    public int  getIdKassir() throws ClassNotFoundException, SQLException{
       String url = "jdbc:mysql://localhost:3306/kursValyut?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC";        
       String user = "root";
       String password = "toor";
       String name =  (String) selectKassir.getSelectedItem();
       String query3 = "SELECT Code_staff FROM staff WHERE name_staff = '" + name +  "' ";
       int idStaff=0;
       
       try{
           Class.forName("com.mysql.cj.jdbc.Driver");
           con = DriverManager.getConnection(url, user, password);
           stm = con.createStatement();
           rst = stm.executeQuery(query3);
           while (rst.next()){
               idStaff = rst.getInt(1);
           }
           
           
          
       }catch(Exception e){
           e.printStackTrace();
       }
       return idStaff;
        
    }
    
    
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, SQLException {
        MainGUI main = new MainGUI();
        main.setVisible(true);
        
    }
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainGUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_addClient;
    private javax.swing.JPanel btn_oper;
    private javax.swing.JPanel btn_search;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JTextField fieldGetContract;
    private javax.swing.JTextField fieldGetDate;
    private javax.swing.JTextField fieldGetName;
    private javax.swing.JTextField fieldGetPassport;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelEU;
    private javax.swing.JLabel jLabelUSD;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JComboBox<String> selectKassir;
    private javax.swing.JTable tableClient;
    private javax.swing.JPanel userSidePanel;
    // End of variables declaration//GEN-END:variables
}
