/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiFrames.framseDB;

import Tester.DbConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class SignGUI extends MainDialog {

    /**
     * Creates new form SignGUI
     * 
     */
    private Connection con;
     private DbConnection menager;
     private MainDialog dialog;
    
    
    public SignGUI(DbConnection menaging) {
        initComponents();
      this.menager = menaging;
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setFocusable(false);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(80, 179, 179));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GuiFrames/framseDB/images/user.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 28, -1, -1));

        jTextField1.setBackground(new java.awt.Color(80, 179, 179));
        jTextField1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField1.setDoubleBuffered(true);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 121, 204, 30));

        jPasswordField1.setBackground(new java.awt.Color(80, 179, 179));
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPasswordField1.setDoubleBuffered(true);
        jPasswordField1.setFocusCycleRoot(true);
        jPasswordField1.setOpaque(true);
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 213, 204, 30));

        jButton1.setBackground(new java.awt.Color(80, 179, 179));
        jButton1.setText("Sign");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jButton1.setContentAreaFilled(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 276, 130, 26));

        jLabel2.setText("login");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel3.setText("password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dialog = new MainDialog();
        try {
            // TODO add your handling code here:
            if (authenticate()){
                dialog.setEnum(enumForDialog.OK);
                dialog.close();
            }
        } catch (Exception ex) {
            
        }
                
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
     protected boolean authenticate() throws Exception{
        
        String login = null;
        char[] psw =null ;
                   
        try{
            login = jTextField1.getText().trim();
            psw = jPasswordField1.getPassword();
            if (login.length() == 0 || psw.length == 0 )
                throw new Exception("Логин или пароль не указаны");
        }
            catch(Exception e){
             JOptionPane.showMessageDialog(null, e.getMessage(), "Ошибка ввода данных! ", JOptionPane.ERROR_MESSAGE);
             jPasswordField1.setText(null);
             return false;
             }
        try{
            String str = new String(psw);
            con = connect(login, str);
            if(con == null)
                throw new Exception("Логин или парол указан не верно! ");
             // menager.setConnection(con);
            
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Ошибка входа в систему ! ", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            System.out.println(e);
            
            jPasswordField1.setText(null);
           return false;
        }
        return true;
    }
    
    private Connection connect(String login, String password) throws ClassNotFoundException, SQLException, InstantiationException, IllegalAccessException{
        Locale.setDefault(Locale.ENGLISH);
       String url = "jdbc:mysql://localhost:3306/kursValyut?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC";
       try{    
       try{
                Class.forName("com.mysql.cj.jdbc.Driver");
            }
            catch(ClassNotFoundException ne){
                ne.printStackTrace();
                
            }
            con = DriverManager.getConnection(url, login, password);
           con.setAutoCommit(false);
           //Statement stm = con.createStatement();
            return con;
       }
       catch(SQLException e){
           e.printStackTrace();
           return null;
       }
        
    
    }

  
//    public static void main(String[] args){
//        SignGUI active = new SignGUI();
//        active.setVisible(true);
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
